### ISSUE TITLE
Code review - Hit the API

### ISSUE THREAD

**Issue by Alejandroq12** [J-C-S-V/leaderboard-project#3]
Hello, Juan.
Good Job so far!

Great job doing this project. Your code is clean and you are following best practices.

I just will suggest some changes that may improve your project even more:

- When using Webpack, it is generally not necessary to manually add a script tag in your `index.html` file, as Webpack can take care of injecting the necessary script tags for your bundled JavaScript files. Instead, you can use the HtmlWebpackPlugin to generate an index.html file with the appropriate script tags injected.
- it could be great to add ARIA (Accessible Rich Internet Applications) labels to your HTML.

- But I can see that you have missed a very important requirement. That is even missed by both of your code reviewers. 
-- "Create a new game with the name of your choice by using the API.
--- Make sure that you saved the ID of your game that will be returned by API."
--- This means that API should be called to get the `unique game id` and then save that in the localStorage like it is done for the tokens. 
-- Second important thing is to make use of `ES6` modules. `import` and `export` them to make your application robust.

Rest everything is working fine.

**Comment by J-C-S-V** [comment]
Thank you for your feedback team. I fix almost all the suggestions 😊

Regards!
